### ISSUE TITLE
FleurCalculation, verdi calculation inputcat should show inp.xml

### ISSUE THREAD

**Issue by broeder-j** [JuDFTteam/aiida-fleur#15]
this was not possible before, but there was an adjustment in AiiDA. Maybe know it is.

(You have to set some variable in the plugin, but in the case of a fleurcalculation this can only be set AFTER the fleurinp data node was connected to the calculation.

**Comment by Tseplyaev** [comment]
For me it seems impossible since inp.xml is always located in another folder (either Fleurinp folder or previous calculation folder). To use ``verdi calculation inputcat`` we should copy inp.xml from there to the FleruCalculation input folder, which will generate unnecessary file duplication in the repository. We do not want that and I think we shall just not use this feature for Fleur calculation.
