### ISSUE TITLE
reduce size of pypi install

### ISSUE THREAD

**Issue by ltalirz** [JuDFTteam/aiida-fleur#45]
As of today, after installing aiida-fleur 0.6.2 via pip, the package takes up 38MB on disk space, 36MB of which is in tests/files (e.g. `local_exe` (??) ).

Can this be improved?

A few other packages for comparison
```
1.4M	paramiko
1.5M	setuptools
3.5M	tornado
5.8M	IPython
8.2M	sqlalchemy
38M  	aiida-fleur
```

**Comment by broeder-j** [comment]
Thanks for pointing this out. I have not checked on the size.

The executables (folder local_exe) can be removed and I will do so in further releases (not add them). This was a beginning for a way of some real workflow tests.

The other 2.5 MB are currently output files for parser tests. I leave them for now in, but some of the larger ones can be shorten and still be good for the test cases.

**Comment by broeder-j** [comment]
To update to the current status, the following files should be shorted:
3.2M	./aiida_fleur/tests/files
3.5M	./aiida_fleur/tests/old_todo
5.0M	./docs/source/images
1.6M	./docs/source/user_guide/workflows/images
13M	        ./examples/out_xml_files

**Comment by broeder-j** [comment]
1.4M ./aiida_fleur/tests/files
36K	./aiida_fleur/tests/old_todo
988K ./examples/out_xml_files
deleted part of the output files not used for tests. there are some larger 500 K input files and still some 300 K + outputfiles because of corelevels and magnetism...

maybe we should consider leaving (moving) the docs, tests and examples out of a pypi release this should result in something < 2 MB, with everything else it is 14 MB currently.

**Comment by ltalirz** [comment]
fyi, we just moved the tests out of aiida-core; the size of the tarball is now 1.1MB
