### ISSUE TITLE
Represent previous calculation as a CalcJob (or FolderData) input node, not RemoteData node

### ISSUE THREAD

**Issue by Tseplyaev** [JuDFTteam/aiida-fleur#59]
To specify previous calculation (to take inp.xml from `Fleurinputgen` or cdn1 from `FleurCalculation`) one needs to pass its RemoteData object.

If I am correct, we always then go through links to find a FolderData of the previous calculation to copy required files. If this is true, I see no point passing RemoteData node. It can be changed to CalcJob (which is easier for a user to use) or FolderData (which is easier to maintain).

**Comment by Tseplyaev** [comment]
It seems it is not allowed to specify a process node as an input.

**Comment by broeder-j** [comment]
Yes in deed it is not, in the open provenance model always data nodes have to go into calculations.
 
But still in aiida-fleur 0.6.3 with aiida_0.12 we had methods which made that possible for convience for the user and workflow developer. One could override use methods (like use_parent_calculation) and the methods found the data node and inputed it correctly in the calculation class, making the provenance right. I opened back then when Process broke use_methods an aiida-core issue, not sure what the status is. Therefore, I am not sure if it can be redone in a certain way now. But overall do you think it is important? Since the usual user will not run FLEUR CalcJobs but ScfWorkChains.

**Comment by broeder-j** [comment]
https://github.com/aiidateam/aiida-core/issues/247

sphuber:This issue is slightly outdated. In `v1.0.0` the legacy job calculation has been removed and one can now only define and submit `Process` sub classes. The functionality that was provided by custom `use_` methods can now be implemented using either the `ProcessBuilder`, an instance of which can be created through the node with `create_restart_builder`, or users can add a `CalculationTools` entry point which exposes custom methods on the `CalcJobNode` produced by running a `CalcJob` process. Closing this until we find a more concrete example of old functionality that can not be replicated in the new system

So it might be possible. If you care feel happy to do so.

**Comment by Tseplyaev** [comment]
@broeder-j 

I fill OK about finding the `FolderData` and other stuff if `RemoteData` is given. For developers it should not cause much a trouble. I think you are right - a user probably never have a problem with this if we make a clear documentation on that. 
However, I meant it is not intuitive to specify RemoteData to copy `inp.xml` and `cdn.hdf` files from the repository. Sometimes `RemoteData` content can be even corrupted (because remote folders were cleaned by IT stuff for example). For me `CalcJobNode` would show much clearer intention to reuse the old calculation: one specifies `CalcJobNode` and we copy what needed from `FolderData` and ,if exists, from `RemoteData`.
Overall, I am quite satisfied with the current implementation and I think we should not change it if it causes much trouble. Originally I thought that it is much easier to fo this but it turned out to be a much more complicated problem.
