### ISSUE TITLE
Enhancements for LDA+U

### ISSUE THREAD

**Issue by janssenhenning** [JuDFTteam/aiida-fleur#87]
Here we collect the things that could be improved in the plugin for calculations with LDA+U

**Comment by janssenhenning** [comment]
These inputs are required to insert a LDA+U calculation:
- AtomSpecies or Group, where LDA+U should be performed (this would create the ldaU tag in the right place)

- The orbital quantum number l

- The Hubbard parameters U and J

- The double counting to be used (l_amf switch)

**Comment by broeder-j** [comment]
Usecases
- Possible one U on each species. @janssenhenning: are there usecases where one wants 2 Us on the same species but different energy windows of cause?
Maybe here it might be nice if inpgen writes already LDA+U tag in the inp.xml which can be 'switched' on
- editing of the density matrix, i.e special initialization....
- ggf selection of different convergence 'strategies'

**Comment by janssenhenning** [comment]
Strategies for converging LDA+U calculations (ranked from least to most "invasive"):

1. More frequent history resets with Anderson mixing
2. Start the calculation with either straight mixing or Anderson mixing and linmix for the density matrix
3. Start the calculation with a fixed density matrix (linmix="T" mixParam="0.0") and converge (not really required) and then allow the density matrix to change

The last point would need to generate the n_mmp_mat files, as it can't be specified in the input file

**Comment by janssenhenning** [comment]
@broeder-j: Okay this would remove the need to create a tag then. Maybe something like setting the l attribute to -1? 

I think if you set U and J to 0.0 this still can have some symmetry implications with second variation SOC

**Comment by broeder-j** [comment]
@janssenhenning Does one want to change l, U, J l_amf sometimes between iterations? So far I used this as fixed input till 'convergence'.

Changes to Fleur required:
- more information in the out.xml: convergence measure for the density matrix

Check if 'n_mmp_mat' file is easy parsable and if it is clear if you want to edit something how to do it. I.e do you know which entry belongs to which atom type/species?
Since the densities are also written to the out.xml file it might not be needed to parse the 'n_mmp_mat' file at all?

Comment to 3.: Reusing a previous 'n_mmp_mat' from a previous calculation would be easy in AiiDA FLEUR. If you want to change it, the user would need to specify the change before the launch of the workchain somehow...

**Comment by janssenhenning** [comment]
@broder-j: No, atleast I never change l,U,J or l_amf during a scf calculation

**Comment by janssenhenning** [comment]
The current format of the n_mmp_mat files could be a bit awkward to parse. This is because the density matrix is complex, but is always written out as 7 numbers per line. 

So two lines correspond to one m index, while every second column is a mp index
The spins and atoms are the smaller problem. All the density matrices are just printed out in the sequence: atom1 Spin-up, atom1 Spin-down, atom2 Spin-up ...

**Comment by broeder-j** [comment]
@janssenhenning: I think we have still to provide an easy way for the user to create the lda+U tag(s).

current basic way to do this is along the line: 
```
newtag= <ldaU l="2" U="8.0" J="0.9" l_amf="F"/> # (etree code to create this)
fm.create_tag('/fleurInput/atomSpecies/species/[@name = "O-1"], newtag)
```
This may not put it in the right place. I think it would append it.
(or eval species first, add tag, then replace species tag)

I suggest to implement lda+U support in the `set_species` method in `xml_util.py`. the current implementation there is wrong (ldaU is an attribute there). The method knows of the order of tags and is used to set los and so on.

This requires however the user to know the species name(s) he wants to do LDA+U on. But he could give certain atoms or kinds a special name before hand to know this. Further I think the user want to be able to say but this on all `O`species.

**Comment by broeder-j** [comment]
The `<ldaU l_linMix="F" mixParam=".050000" spinf="1.000000"/>` is per default in the inp.xml, or? So there is no need to create that tag, only set the attributes. Notice that `spinf` is not unique anymore. (check for magnetic calc+ldaU if there is a problem.)

**Comment by janssenhenning** [comment]
Yes the ldaU tag in the calculationSetup is always present

**Comment by janssenhenning** [comment]
Regarding the setting of ldaU for certain elements (not labels):
As I see it in the ```xml_util``` there is only ```set_species``` and ```set_species_label``` and I don't think its possible to get multiple specific species with these. You can only choose one or all species.

@broeder-j Would it make sense to implement something like ```set_species_element``` to allow for that?

**Comment by broeder-j** [comment]
> @broeder-j Would it make sense to implement something like `set_species_element` to allow for that?
Yes it does, but I would suggest to expand `set_species` with such a feature, instead of implementing a new method:

> Further, I think the user wants to be able to say put this U on all `O` species. So it might make sense to allow for a `all-<element>` as `species_name` input to `set_species`. (list of species xpaths, for loop around). But check if there is already another clear way to do this, because one could get all species names for a certain element and execute then `set_species` on them.

Better: do not just allow for `'all-<element>'`, allow for an arbitrary string i.e implement `species_name='all-<string>'` applies change(s) to all species which name contains `<string>` @Tseplyaev what do you think of this?
   
@janssenhenning: Do you like to implement this as a first task? i.e create a branch, implement this with a small test, then create a pull request, I am happy to review your code and if needed help you. Otherwise, I can implement it, but it will prob take longer then. ;-)

**Comment by janssenhenning** [comment]
@broeder-j Yes I can try to implement this :)

**Comment by janssenhenning** [comment]
@broeder-j The option for ```all-<string>``` is implemented. It turned out to be really easy, because there is existing xpath syntax to search for a contained string.

Should I also add the support for multiple ldaU tags to the same pull request? For this I essentially copied the lo part of ```set_species```

**Comment by broeder-j** [comment]
sure

**Comment by janssenhenning** [comment]
@broeder-j I'm thinking about how to handle the n_mmp_mat files. First of all it might be a good idea to always provide the file with the name ```n_mmp_mat``` (also with HDF) when a calculation is started. This way both versions will always take the data in the n_mmp_mat as the initial density matrix

I wrote a small parser for the n_mmp_mat, which parses it into a dict with the structure

- species_name
   - orbital quantum number
       - spin

The problem is of course, that next to this also the order in which these elements are read in from FLEUR must be stored to be able to write out a new n_mmp_mat file

**Comment by Tseplyaev** [comment]
@janssenhenning 
I am sorry I do not know much about LDA+U calculations, but if you need to reuse generated `n_mmp_mat` file as an input you might consider storing it in the `FleurinpData`. For example, `relax.xml` is copied to the repository and submitted within `FleurinpData` to next relaxation iteration instead of parsing it and submitting as a `Dict` (actually I parse `relax.xml`, but for another reason). However, if you need to modify the content of the input file between Fleur calculations this approach won't be enough and you indeed need a way to parse it and write it out again.

**Comment by janssenhenning** [comment]
@broeder-j: Stuff I would like to have in the output node under a key like 'ldaUinfo':

- General
   - Convergence of the density matrix (is summed over for all ldaU elements at the moment)
   - Total energy correction from LDA+U
- For each LDA+U procedure 
   - maybe some combination of element and species-name to make it useful in all situations (renamed species)??
   - essentially all attributes from the inp.xml ldaU tag (l,U,J l_amf can maybe be replaced by a string either being 'FLL' or 'AMF')
   - There are also angles you can specify there for a rotated density matrix but I do not know much about this feature
      maybe Gregor knows if that is something that should be easily accessible
